steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/sec-460-devsecops/streamlit-app', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/sec-460-devsecops/streamlit-app']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args: ['run', 'deploy', 'streamlit-app',
         '--image', 'gcr.io/sec-460-devsecops/streamlit-app',
         '--platform', 'managed',
         '--region', 'us-central1',
         '--allow-unauthenticated']

images:
- 'gcr.io/sec-460-devsecops/streamlit-app'

options:
  logging: CLOUD_LOGGING_ONLY