steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/sec-460-devsecops/streamlit-app', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/sec-460-devsecops/streamlit-app']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args: ['run', 'deploy', 'streamlit-app',
         '--image', 'gcr.io/sec-460-devsecops/streamlit-app',
         '--platform', 'managed',
         '--region', 'us-west2',
         '--allow-unauthenticated']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud run services add-iam-policy-binding streamlit-app \
        --member="allUsers" \
        --role="roles/run.invoker" \
        --platform managed \
        --region us-west2

images:
- 'gcr.io/sec-460-devsecops/streamlit-app'

options:
  logging: CLOUD_LOGGING_ONLY